# Local image overrides.
# Edit the image tags below to swap in locally-built images.
# Run `make docker-local-branches` to build local/* images first, then set
# the tag to e.g. local/trade-imports-animals-frontend.

services:

  trade-imports-animals-frontend:
    image: defradigital/trade-imports-animals-frontend:latest

  trade-imports-animals-backend:
    image: defradigital/trade-imports-animals-backend:latest

  trade-imports-animals-admin:
    image: defradigital/trade-imports-animals-admin:latest
