services:
  trade-imports-animals-frontend:
    build:
      context: ../../repos/trade-imports-animals-frontend
      target: development
    image: ''
    volumes:
      - ../../repos/trade-imports-animals-frontend/src:/home/node/src
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:3000/health']
      interval: 5s
      start_period: 30s
      retries: 10

  trade-imports-animals-admin:
    build:
      context: ../../repos/trade-imports-animals-admin
      target: development
    image: ''
    volumes:
      - ../../repos/trade-imports-animals-admin/src:/home/node/src
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:3001/health']
      interval: 5s
      start_period: 30s
      retries: 10

  trade-imports-animals-backend:
    build:
      context: ../../repos/trade-imports-animals-backend
      target: dev-run
    image: ''
    volumes:
      - ../../repos/trade-imports-animals-backend/src:/app/src

  trade-imports-stub:
    build:
      context: ../../repos/trade-imports-stub
      target: development
    image: ''

  trade-imports-dynamics-gateway:
    build:
      context: ../../repos/trade-imports-dynamics-gateway
      target: dev-run
    image: ''
    volumes:
      - ../../repos/trade-imports-dynamics-gateway/src:/app/src

  trade-imports-reference-data:
    build:
      context: ../../repos/trade-imports-reference-data
      target: development
    image: ''
