@startuml
'https://plantuml.com/deployment-diagram

@startuml
  left to right direction
  label "This is the end state for our environment mappings. We might choose to stub dev, TBC"

  package "trade-imports-dynamics-gateway" {
    node "Dev"  as cdp_dev
    node "Test" as cdp_test
    node "Production" as cdp_prod
  }

  package "ASB fronting PIMS" {
    node "tst"    as asb_tst
    node "pre"    as asb_pre
    node "Production" as asb_prd
  }

  cdp_dev  --> asb_tst : maps to
  cdp_test --> asb_pre : maps to
  cdp_prod --> asb_prd : maps to

@enduml