@startuml
'https://plantuml.com/deployment-diagram

@startuml
  left to right direction
  label "The initial state of the mappings, while we harden the integration. This protects PRE and PROD PIMS."

  package "trade-imports-dynamics-gateway" {
    node "Dev"  as cdp_dev
    node "Test" as cdp_test
  }

  package "ASB fronting PIMS" {
    node "dev"    as asb_dev
    node "tst"    as asb_tst
  }

  cdp_dev  --> asb_dev : maps to
  cdp_test --> asb_tst : maps to

@enduml